# Site settings
title: Graham Freeman - SuperNerdDad
email: graham@jahiel.net
tel: +1-510-560-7900
description: > # this means to ignore newlines until "baseurl:"
  <a href=https://looking-beyond-tomorrow.org/ target=_blank>Thinking long-term</a>. Also, some <a href=https://xkcd.com/288/ target=_blank>irreverence</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graham-freeman.info" # the base hostname & protocol for your site
twitter_username: gjmf
github_username: gjmf
author:
  twitter: gjmf

# Build settings
markdown: kramdown

exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
