# Site settings
title: Graham Freeman
email: graham@jahiel.net
tel: +1-510-898-6772
description: > # this means to ignore newlines until "baseurl:"
  Thinking long-term. Also, some <a href=https://xkcd.com/288/ target=_blank>irreverence</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graham-freeman.info" # the base hostname & protocol for your site
#twitter_username: gjmf
github_username:  gjmf

# Build settings
markdown: kramdown

exclude: [vendor]

gems:
  - jekyll-sitemap
