# Site settings
title: Graham Freeman - SuperNerdDad
email: graham@jahiel.net
tel: +1-510-560-7900
signal_fingerprint: 05 e7 1a 62 95 1f cf da c3 8d 99 15 6d 20 ac ab 0a 40 6f 10 e2 f1 a2 eb dd 93 91 6e 98 55 a5 82 04
description: > # this means to ignore newlines until "baseurl:"
  Thinking long-term. Also, some <a href=https://xkcd.com/288/ target=_blank>irreverence</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graham-freeman.info" # the base hostname & protocol for your site
twitter_username: gjmf
github_username: gjmf
author:
  twitter: gjmf

# Build settings
markdown: kramdown

exclude: [vendor]

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
